const ENDPOINTS = [
  {
    id: 'summarize',
    label: 'Summarize',
    path: '/api/v1/summarize',
    fieldName: 'text',
    minLength: 50,
    maxLength: 50000,
  },
  {
    id: 'rewrite',
    label: 'Rewrite',
    path: '/api/v1/rewrite',
    fieldName: 'text',
    minLength: 10,
    maxLength: 10000,
  },
  {
    id: 'keywords',
    label: 'Extract Keywords',
    path: '/api/v1/extract/keywords',
    fieldName: 'text',
    minLength: 20,
    maxLength: 50000,
  },
  {
    id: 'headlines',
    label: 'Headlines',
    path: '/api/v1/headlines',
    fieldName: 'text',
    minLength: 20,
    maxLength: 5000,
  },
  {
    id: 'seo',
    label: 'SEO Meta',
    path: '/api/v1/seo/meta',
    fieldName: 'text',
    minLength: 50,
    maxLength: 10000,
  },
  {
    id: 'email',
    label: 'Email Subjects',
    path: '/api/v1/email/subject-lines',
    fieldName: 'text',
    minLength: 20,
    maxLength: 5000,
  },
  {
    id: 'tone',
    label: 'Translate Tone',
    path: '/api/v1/translate/tone',
    fieldName: 'text',
    minLength: 10,
    maxLength: 10000,
    defaultParams: { targetTone: 'professional' },
  },
  {
    id: 'repurpose',
    label: 'Repurpose',
    path: '/api/v1/repurpose',
    fieldName: 'text',
    minLength: 50,
    maxLength: 10000,
  },
  {
    id: 'compare',
    label: 'Compare Texts',
    path: '/api/v1/compare',
    fieldName: 'text1',
    minLength: 10,
    maxLength: 10000,
    dualInput: true,
  },
];

export default ENDPOINTS;
